# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f493ac7b68918fc427c9410d7bdedcf5a30c247c5630175a47d99c1019eaf89999bd69f106779383abf762a3aa3eaa9b4a27e8e0d5b02e1c966b5b25fdd3900

test:
  secret_key_base: 5c49dbe31cab1a2ab32c884686e4d6551b0f263579650226659ea3d634b805c0dba5ad3544453a5b11270a8b2116addb5f099ee53b6a7a536e353b057a7d3dc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
